# Generated by Django 5.1.6 on 2025-02-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('image_based', 'Image Based')], default='multiple_choice', max_length=20)),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/')),
            ],
        ),
    ]
