# Generated by Django 5.1.6 on 2025-02-26 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_options_optionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
