# Generated by Django 5.1.6 on 2025-03-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_testsession_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='questions',
            field=models.ManyToManyField(related_name='test_sessions', to='quiz.question'),
        ),
    ]
