# Generated by Django 5.1.6 on 2025-03-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_useranswer_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='hint',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
