# Generated by Django 5.1.6 on 2025-03-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_useranswer_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
