# Generated by Django 5.1.6 on 2025-03-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_testsession_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
