# Generated by Django 5.1.6 on 2025-04-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_testsession_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shared', 'Shared'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
