# Generated by Django 5.1.6 on 2025-04-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_review_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='poll_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
