# Generated by Django 5.1.6 on 2025-05-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_testsession_poll_url'),
    ]

    operations = [
    ]
